### ISSUE TITLE
Opening UI-  3DXML not found!

### ISSUE THREAD

**Issue by Schizo** [Terrev/3DXML-to-OBJ#4]
Not sure how to use this program, but when I do 

1) launch  **3DXML to OBJ v1.8.0 64-bit.exe**
2) Put **"myfile.3DXML"** under FIlename (which lives in the same folder as the exe)
3) pressing "Convert"

the textfield of "**FileName**" changes to **"3DXML not found!"**

**Comment by Terrev** [comment]
They go in the Models folder - see the guide linked in the readme: https://www.rockraidersunited.com/topic/7897-3dxml-to-obj-converts-ldd-model-captures-to-obj/
