### ISSUE TITLE
Cannot find corresponding file

### ISSUE THREAD

**Issue by simonasdmd** [Terrev/3DXML-to-OBJ#6]
I put my 3DXML file in the corresponding path. But no files were found.
Why is that?

![image](https://user-images.githubusercontent.com/42527845/77130963-cf122b80-6a94-11ea-8a66-54956a572286.png)

![image](https://user-images.githubusercontent.com/42527845/77131012-ff59ca00-6a94-11ea-8eec-b94b7fd4e8b2.png)

this is my data：

[JCS-D A.1.3dxml.zip](https://github.com/Terrev/3DXML-to-OBJ/files/4357739/JCS-D.A.1.3dxml.zip)

**Comment by Terrev** [comment]
The internals of this file seem to be almost completely different from the 3DXML files generated by 3DVIA Printscreen - going by the metadata inside, it seems it may have been created by/exported from some other software. The 3DXML format supported by this program has all the 3D data stored in, well, XML - while this file has all that data stored in multiple binary files; it's essentially a different format altogether. It would require creating an entirely new program to load, sorry.

**Comment by simonasdmd** [comment]
This data is exported by CATIA itself. Save as 3DXML format.

**Comment by simonasdmd** [comment]
![image](https://user-images.githubusercontent.com/42527845/78761437-2715c100-79b5-11ea-8153-3571ba6b74de.png)
