### ISSUE TITLE
Most of ripped content is missing when converted to OBJ

### ISSUE THREAD

**Issue by vrpixel** [Terrev/3DXML-to-OBJ#9]
For example, when I use 3DVIA to capture COD1 scene, it looks as expected with offial 3D XML Player, however after converting it to OBJ with this tool, it's like 90% of stuff is missing.

**Comment by Terrev** [comment]
Yes, this tool is very specifically tailored to LEGO Digital Designer - it's not a general purpose converter; the 3DXML format has many ways of storing things. Handling captures from other programs or other flavors of the 3DXML format is way outside the scope of this project, sorry.
